# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install build deps
      run: sudo sh -c "apt update -y && apt install build-essential libgtk2.0-dev -y"
    - name: clone jcef source
      run: git clone https://bitbucket.org/chromiumembedded/java-cef.git src
    - name: build
      run: cd src && mkdir jcef_build && jcef_build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. && make -j4 && cd ../tools && sh compile.sh linux64 && sh make_distrib.sh linux64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
       name: artifact
       path: src/binary_distrib/*
      
      
    
